### ISSUE TITLE
Involve mouseover when a mouse is detected

### ISSUE THREAD

**Issue by verlok** [GoogleChromeLabs/quicklink#126]
Let’s start with the congratulations on this script, it’s very useful and we’ve already activated it in production on some of our e-commerce websites.

**Is your feature request related to a problem? Please describe.**
The problem is that on desktop and other large devices, a large number of requests is fired at our network infrastructure (CDN, Origin). 

**Describe the solution you'd like**
When any mouse move is detected, switch from the _IntersectionObserver mode_ to the _mouse pointer mode_ to prefetch the links. 
This would work for both computers with touch screens (a mouse movement is not detected, use the IntersectionObserver) and tablets with mouse attached (a mouse movement is detected, use the mouse pointer).

**Comment by coliff** [comment]
Hi @verlok - are you suggesting that'd you prefer that prefetching would only occur on mouse-over a link (rather than all links within the viewport)? If so, I think https://instant.page/ maybe a solution more suitable to your needs as that only preloads on hovering over a link. If that isn't what you mean then  could you please clarify on what the difference would be in the prefetching ?

**Comment by verlok** [comment]
We’re using instantPage on a website and QuickLink on another website, and we noticed that QuickLink performs better on smartphone, where lesser links enter the viewport at the same time, whereas on computers too many requests are fired towards the origin servers.
But this can’t be solved with device detection, because there are also mixed situations. The best would be to feature detect the presence of a mouse and use the mouse over event in that case. 
That’s why I asked if Quicklink could do that.

**Comment by dieulot** [comment]
Hi, this is not planned for quicklink but it is planned for instant.page’s next version, which should come out next week.

**Comment by addyosmani** [comment]
@verlok I'd love to unpack your use case a little further. You mentioned that on desktop, you're seeing Quicklink fire a large number of requests. 2.0 (alpha already available via tag) supports near full customization of how much you prefetch or throttle prefetching. Rather than switching heuristics, you could just change your prefetching aggressiveness on desktop vs. mobile, but ultimately this is of course your call.

For transparency (I've shared my opinion on this with @dieulot as well), my position on the mouseover heuristic is that I have not yet seen data (e.g Chrome traces or WebPageTest runs) that can verify it materially improves performance. That's certainly not to say the heuristic doesn't (I'm sure it can!), but without seeing this data it's difficult for me to make a call on exploring more heuristics beyond in-viewport prefetching. 

At most, in the short-term, Quicklink may add documentation for 2.0 to show you how to accomplish this with an optional pattern (it's not a lot of code), but we're currently not planning on adding this as a core feature to the next major release. Instead, we'll be telling Quicklink users that switching between how much you prefetch on mobile vs desktop is our preferred path if concerned about heavy server hits.

**Comment by verlok** [comment]
@addyosmani we should stop talking about desktop and mobile since there is no such sharp distinction anymore. Let’s just say that the issue with too many prefetch is issued on larger devices, which could also be tablets. And tablets could also have a mouse attached to it. 

I think that QuickLink works very effectively but it also uses a lot of resources to accomplish that. That’s why I was proposing to make QuickLink switch to a more conservative approach like using a mouseover event, but only wheb a mouse movement is detected.

**Comment by dieulot** [comment]
This can now be done with instant.page: https://instant.page/v3

**Comment by verlok** [comment]
Nice touch, @dieulot!
I have a question, I’ll open an issue on your GitHub project
