### ISSUE TITLE
possible optimizations through idle detection ?

### ISSUE THREAD

**Issue by LifeIsStrange** [GoogleChromeLabs/quicklink#192]
https://chromestatus.com/feature/4590256452009984
I thought this api might be useful

**Comment by demianrenzulli** [comment]
Hi @LifeIsStrange, thanks for filing this.

The library already provides some options, like [timeout](https://github.com/GoogleChromeLabs/quicklink#optionstimeout) and [timeoutfn](https://github.com/GoogleChromeLabs/quicklink#optionstimeoutfn) to configure the amount of time the browser has to be idle before prefetching.

I believe [IdleDetection](https://chromestatus.com/feature/4590256452009984) would be useful as a higher-level API, to identify user's interactions with the device, rather than browser idle times, but if you have any additional thoughts to share, please, feel free to reopen.

Thanks.
