### ISSUE TITLE
Normalize URLs before checking the `toPrefetch` set

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/quicklink#28]
For example, these three URLs are all equivalent:

```
https://www.google.com
https://www.google.com/
https:\\www.google.com/
```

(That last one is an extreme example, but it’s pretty common to see the first and second variation used interchangeably.) 

When reading an element’s `.href` like in https://github.com/GoogleChromeLabs/quicklink/blob/f9a2ca71638915289d4660dbae64330a14d04730/src/index.mjs#L25, you’d get the following normalized URL for each of those three:

```
https://www.google.com/
```

However, the same normalization is not applied when the user manually passes in URLs: https://github.com/GoogleChromeLabs/quicklink/blob/f9a2ca71638915289d4660dbae64330a14d04730/src/index.mjs#L67

Because of this, the `toPrefetch` set currently ends up with three separate entries in this case, even though all of them normalize to the same URL:

```js
quicklink({
   urls: [
    'https://www.google.com',
    'https://www.google.com/',
    'https:\\www.google.com/',
  ],
});
```

It can be solved by forcing URL normalization before calling `prefetcher` on this line: https://github.com/GoogleChromeLabs/quicklink/blob/f9a2ca71638915289d4660dbae64330a14d04730/src/index.mjs#L67

```diff
-      options.urls.forEach(prefetcher);
+      options.urls.forEach(url => prefetcher(new URL(url).toString()));
```

**Comment by addyosmani** [comment]
This is a great catch. Nice work highlighting the normalization issue, @mathiasbynens ❤️ Given URL has pretty [decent](https://caniuse.com/#search=URL) cross-browser support, I'm happy for us to use your suggested change. 

Do you want to PR in that one-liner? If not, happy to patch directly :)

**Comment by lukeed** [comment]
Nothing gets added to `toPrefetch` when you pass in an `options.url` list. The `prefetcher` only looks to remove Set entries – additions are made thru the "scraped" links which are already normalized as you mentioned.

That said, we should still probably normalize so that the `prefetch` itself can send valid requests. Eg, `fetch('https:\\www.google.com/')` will fail.

IMO, normalization should happen here: https://github.com/GoogleChromeLabs/quicklink/blob/master/src/index.mjs#L37

It'll be redundant for the "scraped" links, but it avoids adding a new function 😇

**Comment by addyosmani** [comment]
@lukeed Hah. Avoiding the addition of a new function is fair. Were you thinking of normalization around L37 looking similar to this?

```js
function prefetcher(url) {
  const nURL = new URL(url).toString();
  toPrefetch.delete(nURL);
  prefetch(nURL, observer.priority);
}
```

**Comment by addyosmani** [comment]
Closed by https://github.com/GoogleChromeLabs/quicklink/pull/37. Thanks again!
