### ISSUE TITLE
How to use with react-native?

### ISSUE THREAD

**Issue by arximughal** [GoogleChromeLabs/quicklink#30]
Would this work by default with react-native projects? Or any idea how to make it work in react-native?

**Comment by HOUCe** [comment]
Hey @arximughal @addyosmani , 

I think quicklink can't work with React native/React projects by default. But we can use this anyway by creating a React native/React component which implement with quicklink.
I've made one, check [react-quicklink-component](https://www.npmjs.com/package/react-quicklink-component). The `<Quicklink>` component was designed by `render props` pattern and connected with raw quicklink by `ref`.

So, we can use like so:

``` javascript
<Quicklink>
  <Comp1>
  ...
  <CompN>
</Quicklink>
```

As for React native, I suppose the philosophy is the same. But the key point is how to collect link url. Quicklink uses `document.querySelectorAll` and iterate the `<a>` tag which seems impossible for React native. We can try with `React.Children.map()` to filter urls.

**Comment by arximughal** [comment]
@HOUCe This sounds really great. I have an app in react-native which uses a lot of images. Fortunately, I get all the URLs for the images before starting a quiz so this component can really really help in that matter as I won't have to filter URLs. Thanks for the component, I'll definitely check it out 🙂

**Comment by addyosmani** [comment]
Thanks for creating https://www.npmjs.com/package/react-quicklink-component, @HOUCe. This is neat. Outside of leveraging `React.children.map()` for this I think your component might be the best option for React native users to take advantage of quicklink's concepts. We otherwise plan to focus on providing a lean core.

I'm going to close up this issue and suggest folks use the above component for RN 👍
