### ISSUE TITLE
Option to ignore certain URLs by extension

### ISSUE THREAD

**Issue by haroldo-ok** [GoogleChromeLabs/quicklink#33]
Doing a quick and dirty test of this library on my personal site, I have noticed that (possibly large) zip download files are being fetched, too... it would be interesting to be able to restrict which kind of URLs would be fetched.

**Comment by lukeed** [comment]
This would be solved by a fully configurable `origins` option, as mentioned in https://github.com/GoogleChromeLabs/quicklink/issues/31#issuecomment-447133127

Another possibility could be to add a new `filter` option, since it's no longer just checking origins. This can apply function(s) or RegExp(s) to any URL. It's then prefetched if the function/RegExp passed.

When paired with `origins[]`, the filter(s) would have to run _after_ the hostname check.

**Comment by addyosmani** [comment]
I'm fully supportive of addressing this feature request via Luke's proposal in #31 (origins, filter). Let's tackle solving this through that implementation.

**Comment by haroldo-ok** [comment]
I agree that adding the possibility of passing a predicate function in order to filter which links should be prefetched would provide lots of flexibility without adding much code to the library.

One detail that I'm thinking, though: some less careful library users may not notice their download links are being prefetched, too... some default filters may come useful for "drop-in" operation.

**Comment by addyosmani** [comment]
Fixed by https://github.com/GoogleChromeLabs/quicklink/commit/1ff35548fe61df8504c118db97e3c88c825e3438. `origins` and `ignores` will be in the next release so filtering will be available shortly.
