### ISSUE TITLE
Does link prefetching work with target="_blank"?

### ISSUE THREAD

**Issue by amxn123** [GoogleChromeLabs/quicklink#87]
I added quicklink to a Chrome extension I have. The thing is, all of my links have the **target="_blank"** attribute, because that's the only way to open up links from the extension popup (otherwise, you click on them and nothing happens).

So far it's adding the <link rel="prefetch"> correctly for each of links, but I don't notice a speed improvement when I click on them.

My question is: is it possible that when a prefetch link is opened in a different tab, the browser simply _forgets_ the fetching?

**Comment by mherchel** [comment]
No, Quicklink will pull down those links assuming they're in the same domain. You can view the network tab within your browser's developer tools to view the files that are being pulled down.

**Comment by demianrenzulli** [comment]
Hey guys,  I'll add my response and close the issue, let me know if you need any other clarifications:

Quicklink **does work** for _target="_blank"_. The only caveat is that, if you are opening links from a different origin, you should [allow them](https://github.com/GoogleChromeLabs/quicklink#allow-all-origins) when calling `quicklink.listen()`.

Testing this is a bit tricky, because when you open a new tab in Chrome, by default DevTools is not opened. For that reason that request is not recorded in the Network tab. 
Fortunately, there's an option "Auto open DevTools for popups", in DevTools settings (that you can access by clicking on the 3 points at the corner of DevTools). That would allow you to see the prefetch links being picked up from the prefetch cache when you click on any of these links.

Here is a demo:

1. Open [this site](https://quicklink-target-blank.glitch.me/) in Chrome. The demo contains two links wtih target="_blank", for same and cross origin respectively.
2. Reload the page, and check the Network tab, to see that both links are prefetched.
3. Click no any of them. If you enabled the option mentioned before in DevTools, you'll see the links being picked up from he prefetch cache, instead of the network.

Cheers.
