### ISSUE TITLE
Is quick link works for <iframe>?

### ISSUE THREAD

**Issue by maheshwaghmare** [GoogleChromeLabs/quicklink#94]

**Comment by mherchel** [comment]
No, currently Quicklink only works for hyperlinks.

That being said, I'm not sure it's needed. The browser will load the iframe content automatically (unlike pages linked from `<a>` tags).

**Comment by domfarolino** [comment]
While QL does not work for `<iframe>`, [LazyLoading](https://addyosmani.com/blog/lazy-loading/) does, which may be of interest to you. It might be nice to somehow either extend LazyLoading to `<iframe>`s (unlikely though) or introduce a new primitive that accomplishes what Quicklink does, if the benefits would be strong enough to justify a native solution.

**Comment by demianrenzulli** [comment]
Hi folks,

Proceeding to close this issue, since the previous answer is correct.

I would only add that, since you can't rely on the automaitc in-viewport prefetching logic, you can always explicitly call `quicklink.prefetch('url')`, as explained [here](https://github.com/GoogleChromeLabs/quicklink#programmatically-prefetch-urls) for the links you want to prefetch within the iframe.

Just make sure to [allow any third party origin](https://github.com/GoogleChromeLabs/quicklink#specify-a-custom-list-of-allowed-origins), if you need to do so.
